### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76cc6f]

### ISSUE THREAD

**Issue by tmeinlschmidt** [blockwatch-cc/tzindex#49]
latest tzindex version

    INFO MAIN Blockwatch Data Inc. TzIndex -- v15.0.0 49e3e0e

used params

    tzindex -db.path=/data/tzindex -db.engine=bolt -rpc.url=http://somehostonlima -light -notls

1st issue - complaining about ticket.db

````
2023/02/20 08:31:31.929478 WARN MAIN Missing config file, using default values.
2023/02/20 08:31:31.929552 INFO MAIN Blockwatch Data Inc. TzIndex -- v15.0.0 49e3e0e
2023/02/20 08:31:31.929559 INFO MAIN (c) Copyright 2018-2023 Blockwatch Data Inc.
2023/02/20 08:31:31.929562 INFO MAIN Go version go1.20
2023/02/20 08:31:31.929568 INFO MAIN Starting on 64 cores
2023/02/20 08:31:31.929978 INFO MAIN Using bolt database /data/tzindex
2023/02/20 08:31:31.932042 INFO BLOC Initializing blockchain crawler in sync mode.
2023/02/20 08:31:31.932712 INFO BLOC Creating ticket index.
2023/02/20 08:31:31.933478 INFO BLOC Closing account index.
2023/02/20 08:31:31.934038 INFO BLOC Closing balance index.
2023/02/20 08:31:31.934485 INFO BLOC Closing contract index.
2023/02/20 08:31:31.935025 INFO BLOC Closing storage index.
2023/02/20 08:31:31.935531 INFO BLOC Closing constant index.
2023/02/20 08:31:31.935989 INFO BLOC Closing block index.
2023/02/20 08:31:31.936429 INFO BLOC Closing op index.
2023/02/20 08:31:31.936872 INFO BLOC Closing event index.
2023/02/20 08:31:31.937300 INFO BLOC Closing flow index.
2023/02/20 08:31:31.937733 INFO BLOC Closing chain index.
2023/02/20 08:31:31.938155 INFO BLOC Closing supply index.
2023/02/20 08:31:31.938580 INFO BLOC Closing bigmap index.
2023/02/20 08:31:31.939020 INFO BLOC Closing metadata index.
2023/02/20 08:31:31.939436 INFO BLOC Closing ticket index.
Error: error initializing crawler: creating ticket database: pack: creating database: database file "/data/tzindex/ticket.db" exists
````

so I had to rename ticket.db (it was from the previous version tzindex, with v14 support only), then it started and continued like that

````
2023/02/20 08:31:49.445677 WARN MAIN Missing config file, using default values.
2023/02/20 08:31:49.445744 INFO MAIN Blockwatch Data Inc. TzIndex -- v15.0.0 49e3e0e
2023/02/20 08:31:49.445749 INFO MAIN (c) Copyright 2018-2023 Blockwatch Data Inc.
2023/02/20 08:31:49.445756 INFO MAIN Go version go1.20
2023/02/20 08:31:49.445763 INFO MAIN Starting on 64 cores
2023/02/20 08:31:49.447148 INFO MAIN Using bolt database /data/tzindex
2023/02/20 08:31:49.448619 INFO BLOC Initializing blockchain crawler in sync mode.
2023/02/20 08:31:49.449231 INFO BLOC Creating ticket index.
2023/02/20 08:31:49.469937 INFO BLOC Initializing account index.
2023/02/20 08:31:49.631092 INFO BLOC Initializing balance index.
2023/02/20 08:31:50.548491 INFO BLOC Initializing contract index.
2023/02/20 08:31:50.837227 INFO BLOC Initializing storage index.
2023/02/20 08:31:51.784875 INFO BLOC Initializing constant index.
2023/02/20 08:31:51.786180 INFO BLOC Initializing block index.
2023/02/20 08:31:51.888427 ERRO DATA pack: header decode for table block pack 0000005a: pack: reading bloom filter: short buffer
2023/02/20 08:31:51.888449 WARN DATA pack: block table has corrupt or missing statistics! Re-scanning table. This may take some time...
2023/02/20 08:31:53.570051 INFO BLOC Initializing op index.
2023/02/20 08:31:55.374445 INFO BLOC Initializing event index.
2023/02/20 08:31:55.375667 INFO BLOC Initializing flow index.
2023/02/20 08:31:57.002874 INFO BLOC Initializing chain index.
2023/02/20 08:31:57.021798 INFO BLOC Initializing supply index.
2023/02/20 08:31:57.038513 INFO BLOC Initializing bigmap index.
2023/02/20 08:31:59.953758 INFO BLOC Initializing metadata index.
2023/02/20 08:31:59.955201 INFO BLOC Initializing ticket index.
2023/02/20 08:31:59.956317 INFO BLOC Connecting to RPC server.
2023/02/20 08:31:59.959242 INFO BLOC Closing account index.
2023/02/20 08:32:00.086516 INFO BLOC Closing balance index.
2023/02/20 08:32:00.105579 INFO BLOC Closing contract index.
2023/02/20 08:32:00.976140 INFO BLOC Closing storage index.
2023/02/20 08:32:01.005504 INFO BLOC Closing constant index.
2023/02/20 08:32:01.008819 INFO BLOC Closing block index.
2023/02/20 08:32:01.134209 INFO BLOC Closing op index.
2023/02/20 08:32:01.235399 INFO BLOC Closing event index.
2023/02/20 08:32:01.237799 INFO BLOC Closing flow index.
2023/02/20 08:32:01.270379 INFO BLOC Closing chain index.
2023/02/20 08:32:01.288975 INFO BLOC Closing supply index.
2023/02/20 08:32:01.315941 INFO BLOC Closing bigmap index.
2023/02/20 08:32:01.539708 INFO BLOC Closing metadata index.
2023/02/20 08:32:01.541902 INFO BLOC Closing ticket index.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76cc6f]

goroutine 1 [running]:
blockwatch.cc/tzgo/tezos.(*Params).ForNetwork(0x0, {{0xf0?, {0xc00037d4d0?, 0xc000739600?, 0x0?}}})
	/go/src/tzindex/vendor/blockwatch.cc/tzgo/tezos/protocols.go:100 +0x4f
blockwatch.cc/tzindex/etl.(*Crawler).Init(0xc000620360, {0xdd2df0?, 0xc00013a000?}, {0xb2c71d, 0x4})
	/go/src/tzindex/etl/crawler.go:436 +0xd86
main.runServer()
	/go/src/tzindex/cmd/tzindex/server.go:108 +0xdcd
main.run()
	/go/src/tzindex/cmd/tzindex/main.go:32 +0x2b5
main.main()
	/go/src/tzindex/cmd/tzindex/main.go:17 +0x1d
````

**Comment by echa** [comment]
Sorry for the inconvenience, this touches two different issues. 

TL;TR: please re-index from scratch

1. The v15 database schema differs from v14 (new token index database and several changes to other database models). So far we haven't shipped migration tooling as full db rebuild times are still 'relatively' low and implementing migrations is more time consuming than rebuilding from scratch. This point will change in a few versions, but we need to refactor parts of the database layer first.
2. The segfault is an indirect result of the non-existent migration. A missing index database makes a part of the init code fail early so that a list of deployed protocols is not loaded which in turn yields a nil ptr when looking up the most recent protocol and Baaam.

Commit 810b596 bumps the db schema version to make the indexer fail gracefully and tell you the schema has changed and a rebuild is required.
